server:
  port: 8071

spring:
  application:
    name: shop-user
  cloud:
    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
#        prefix: ${spring.application.name}
#        file-extension: yml
#        namespace: 1d75ab91-2bba-4bdc-8479-7c63c5a30321
#        group: shop-group
      discovery:
        server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tjgx_shop?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password:
  sleuth:
    sampler:
      probability: 1.0

###设置feign客户端超时时间
ribbon:
  ReadTimeout: 5000      # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ConnectTimeout: 5000   # 指的是建立连接后从服务器读取到可用资源所用的时间。

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml

#showSql
logging:
  level:
    com:
      tjgx:
        user:
          mapper: debug

seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: 1d75ab91-2bba-4bdc-8479-7c63c5a30321
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : SEATA_GROUP
      namespace: 1d75ab91-2bba-4bdc-8479-7c63c5a30321