server:
  port: 8061

spring:
  application:
    name: shop-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: shop_order
        uri: lb://shop-order
        predicates:
        - Path=/model_order/**
        filters:
        - StripPrefix=1
      - id: shop_product
        uri: lb://shop-product
        predicates:
        - Path=/model_product/**
        filters:
        - StripPrefix=1
