server:
  port: 8061

# 开启 feign 的熔断功能
feign:
  sentinel:
    enabled: true

###设置feign客户端超时时间
ribbon:
  ReadTimeout: 5000      # 指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ConnectTimeout: 5000   # 指的是建立连接后从服务器读取到可用资源所用的时间。

spring:
  application:
    name: shop-gateway
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: 1d75ab91-2bba-4bdc-8479-7c63c5a30321
        group: shop-group
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
      - id: shop_order
        uri: lb://shop-order
        predicates:
        - Path=/shop-order/**
        filters:
        - StripPrefix=1
      - id: shop_product
        uri: lb://shop-product
        predicates:
        - Path=/shop-product/**
        filters:
        - StripPrefix=1
